# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161022_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='entities',
            field=models.ManyToManyField(to='main.Entity_Class'),
        ),
    ]
