# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161022_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='password',
            field=models.CharField(default='password', max_length=30),
        ),
    ]
