# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_entity_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity_class',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='entity_class',
            name='entity',
        ),
        migrations.AddField(
            model_name='entity',
            name='classes',
            field=models.ManyToManyField(to='main.Classes'),
        ),
        migrations.AddField(
            model_name='entity',
            name='karma',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='entities',
            field=models.ManyToManyField(to='main.Entity'),
        ),
        migrations.DeleteModel(
            name='Entity_Class',
        ),
    ]
