# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20161022_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='karma',
            new_name='honey',
        ),
    ]
