# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20161022_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='classes',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Classes'),
        ),
    ]
