# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_studysession_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='in_session',
            field=models.BooleanField(default=False),
        ),
    ]
